---
- block:
  - name: Install EPEL repository on CentOS
    yum:
      name: 'epel-release'
      state: present
      update_cache: true

  - name: Install necessary packages on CentOS
    yum:
      name: "{{ gogrepo_CentOS_packages }}"
      state: present
      update_cache: true
  become: true
