---
- include_tasks: "gogrepo_{{ ansible_distribution }}_tasks.yml"

- block:
  - name: Create directory for python virtualenv
    file:
      path: "{{ item.root_dir | default('/home/' + item.name + '/gogtool') }}/py_virt"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
    with_items: "{{ gogrepo_users }}"

  - name: Install python dependencies in virtualenv
    pip:
      name: "html2text html5lib pyOpenSSL requests"
      state: present
      virtualenv: "{{ item.root_dir | default('/home/' + item.name + '/gogtool') }}/py_virt"
      virtualenv_command: "/usr/bin/virtualenv-3.4"
      virtualenv_python: "/usr/bin/python3.4"
    with_items: "{{ gogrepo_users }}"

  - name: Download gogrepo
    git:
      repo: https://github.com/Kalanyr/gogrepo.git
      dest: "{{ item.root_dir | default('/home/' + item.name + '/gogtool') }}/gogrepo"
      version: dev
      depth: '1'
      update: true
    with_items: "{{ gogrepo_users }}"

  - name: Set gogrepo script as executable
    file:
      path: "{{ item.root_dir | default('/home/' + item.name + '/gogtool') }}/gogrepo/gogrepoc.py"
      state: file
      mode: u+x
    with_items: "{{ gogrepo_users }}"
  become: true
