---
- include_tasks: "gogrepo_{{ ansible_distribution }}_tasks.yml"

- name: Create temporary directory for download
  tempfile:
    state: directory
  register: gogrepo_temp_dir

- name: Download gogrepo
  get_url:
    url: https://github.com/Kalanyr/gogrepo/archive/dev.zip
    dest: "{{ gogrepo_temp_dir.path }}"
  register: gogrepo_zip_dl_results

- name: Extract gogrepo
  unarchive:
    remote_src: true
    src: "{{ gogrepo_zip_dl_results.dest }}"
    dest: "{{ gogrepo_temp_dir.path }}"

- name: Find extracted gogrepo
  find:
    paths: "{{ gogrepo_temp_dir.path }}"
    patterns: gogrepoc.py
    recurse: true
  register: gogrepo_find_file_results

- block:
  - name: Create necessary directories
    file:
      path: "{{ item.gogrepo.dest }}"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
    with_items: "{{ gogrepo_list }}"

  - name: Create directories for game downloads
    file:
      path: "{{ item.gogrepo.download_dir }}"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
    with_items: "{{ gogrepo_list }}"

  - name: Copy gogrepo to user's directories
    copy:
      remote_src: true
      src: "{{ item[0].path }}"
      dest: "{{ item[1].gogrepo.dest }}/gogrepoc.py"
      owner: "{{ item[1].name }}"
      group: "{{ item[1].name }}"
    with_nested:
      - "{{ gogrepo_find_file_results.files }}"
      - "{{ gogrepo_list }}"

  - name: Create directories for gogrepo scripts
    file:
      path: "{{ item.gogrepo.scripts.path }}"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
    with_items: "{{ gogrepo_list }}"

  - name: Copy gogrepo script templates
    template:
      src: "{{ item[1] }}.sh.j2"
      dest: "{{ item[0].gogrepo.scripts.path }}/{{ item[1] }}.sh"
      owner: "{{ item[0].name }}"
      group: "{{ item[0].name }}"
      mode: u+x
      force: true
    with_nested:
      - "{{ gogrepo_list }}"
      - [ 'gogrepo_verify', 'gogrepo_update', 'gogrepo_download', 'gogrepo_weekly' ]
  become: true
