---
- include_vars: "gogrepo_{{ ansible_distribution }}_vars.yml"
- include_tasks: "gogrepo_{{ ansible_distribution }}_tasks.yml"

# download phase
- name: Create temporary download directory
  tempfile:
    state: directory
  register: gogrepo_temp_dl_dir

- name: Download gogrepo
  get_url:
    url: https://github.com/Kalanyr/gogrepo/archive/dev.zip
    dest: "{{ gogrepo_temp_dl_dir.path }}/gogrepo.zip"

- name: Unpack gogrepo
  unarchive:
    src: "{{ gogrepo_temp_dl_dir.path }}/gogrepo.zip"
    remote_src: true
    dest: "{{ gogrepo_temp_dl_dir.path }}/"

# installation phase
- name: Create necessary directories
  file:
    path: "{{ gogrepo_root_dir }}/{{ item }}"
    state: directory
  with_items: "{{ gogrepo_directories }}"

- name: Install python dependencies in virtualenv
  pip:
    name: "html2text html5lib pyOpenSSL requests"
    state: present
    virtualenv: "{{ gogrepo_root_dir }}/py_virt"
    virtualenv_command: "{{ gogrepo_virtualenv_command }}"
    virtualenv_python: "{{ gogrepo_virtualenv_python }}"

- name: Copy gogrepo to specific directory
  copy:
    src: "{{ gogrepo_temp_dl_dir.path }}/gogrepo-dev/gogrepoc.py"
    remote_src: true
    dest: "{{ gogrepo_root_dir }}/gogrepo/gogrepoc.py"
    mode: u+x
